### ISSUE TITLE
Cannot load templates from github

### ISSUE THREAD

**Issue by vitorfariatomaz** [msshli/arm-visualizer#1]
Hi,
Cannot see template when I click Visualize in the github repo, I'm getting error 500 on the XHR GET
Browsers: Edge; Opera; Chrome;

**Comment by shenglol** [comment]
Hi @vitorfariatomaz ,

Thanks for your feedback. I'm working on this now. Will fix it soon :)

**Comment by shenglol** [comment]
@ytechie Can you deploy the newer version? Just fixed this. Thanks!

**Comment by ytechie** [comment]
Done
