### ISSUE TITLE
Request, increase the width of graph nodes

### ISSUE THREAD

**Issue by dennisroche** [msshli/arm-visualizer#3]
Loading a template with long resource names, it is difficult to tell what resource is which as the name is cut off.

![capture](https://cloud.githubusercontent.com/assets/4949392/17958967/d7e53842-6acf-11e6-92a6-88ce12328fad.PNG)

I'm happy to take a look if you want to mark this as #upforgrabs.

**Comment by ytechie** [comment]
Definitely a regression from v1. V1 would resize the nodes based on the length of the contents.

The easy, yet temporary fix would be to have a tooltip.

@msshli Let Dennis know if he can work on this (just want to make sure you're not)

**Comment by shenglol** [comment]
Hi @dennisroche ,

Thanks for your feedback! I can fix this at once, but if you want to work on this, please feel free to send a pull request.

You might need to modify `DiagramComponent` and `DiagramService`. The width of each node can be calculated based on font size and label's length.

If you have any questions, please let me know :)

**Comment by dennisroche** [comment]
Sorry for the delay. I have PR ready to go up for this.
